<a href="https://colab.research.google.com/github/MichaelOblego/Linear-Algebra-58020/blob/main/Coding_Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Python program to Inverse

In [2]:
import numpy as LA


In [8]:
A = LA.array([[1,2,-1],[2,5,1],[-1,-2,2]])
print ('The matrix:')
print (A)
print ('Inverse of the matrix:')
print(LA.linalg.inv([[1,2,-1],[2,5,1],[-1,-2,2]]))

The matrix:
[[ 1  2 -1]
 [ 2  5  1]
 [-1 -2  2]]
Inverse of the matrix:
[[12. -2.  7.]
 [-5.  1. -3.]
 [ 1.  0.  1.]]


In [9]:
B = LA.transpose(A)
print ('Transpose of matrix:')
print(B)

Transpose of matrix:
[[ 1  2 -1]
 [ 2  5 -2]
 [-1  1  2]]
