<a href="https://colab.research.google.com/github/MichaelOblego/Linear-Algebra-58020/blob/main/Coding_Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Python program to Inverse

In [2]:
import numpy as LA


3x3

In [19]:
A = LA.array([[4,5,-6],[2,5,1],[-1,-2,2]])
print ('The matrix:')
print (A)
print ('Inverse of the matrix:')
print(LA.linalg.inv([[4,5,-6],[2,5,1],[-1,-2,2]]))

The matrix:
[[ 4  5 -6]
 [ 2  5  1]
 [-1 -2  2]]
Inverse of the matrix:
[[ 0.70588235  0.11764706  2.05882353]
 [-0.29411765  0.11764706 -0.94117647]
 [ 0.05882353  0.17647059  0.58823529]]


In [20]:
B = LA.transpose(A)
print ('Transpose of matrix:')
print(B)

Transpose of matrix:
[[ 4  2 -1]
 [ 5  5 -2]
 [-6  1  2]]


4x4

In [21]:
A = LA.array([[3,-2,1,4],[6,7,-8,9],[4,5,6,-7],[9,-8,7,6]])
print(A)

[[ 3 -2  1  4]
 [ 6  7 -8  9]
 [ 4  5  6 -7]
 [ 9 -8  7  6]]


In [22]:
A_inv = LA.linalg.inv(A)

print("Matrix: \n",A)
print("Inverse: \n",A_inv)

x = LA.dot(A, A_inv)
y = LA.array(x, dtype=int) 
print("Check: \n",y)

Matrix: 
 [[ 3 -2  1  4]
 [ 6  7 -8  9]
 [ 4  5  6 -7]
 [ 9 -8  7  6]]
Inverse: 
 [[-0.875       0.14506173 -0.03703704  0.32253086]
 [ 0.75       -0.04938272  0.12962963 -0.27469136]
 [ 1.125      -0.16358025  0.14814815 -0.33179012]
 [ 1.         -0.09259259  0.05555556 -0.2962963 ]]
Check: 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [23]:

A_trans = LA.transpose(A)
print("Matrix: \n",A)
print("Transposed: \n",A_trans)

Matrix: 
 [[ 3 -2  1  4]
 [ 6  7 -8  9]
 [ 4  5  6 -7]
 [ 9 -8  7  6]]
Transposed: 
 [[ 3  6  4  9]
 [-2  7  5 -8]
 [ 1 -8  6  7]
 [ 4  9 -7  6]]
