<a href="https://colab.research.google.com/github/MichaelOblego/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as LA

Problem 1

In [3]:
s1 = LA.array([[1,1,1],[1,0,4],[0,0,5]])
s2 = LA.array([[89],[89],[95]])
t = LA.linalg.inv(s1).dot(s2)
print(t)

[[13.]
 [57.]
 [19.]]


Problem 2

In [8]:
A = LA.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(A)
B = LA.array([[5],[15],[-20]])
print (B)

Apinv = LA.linalg.pinv(A)

x = Apinv.dot(B)
print(x)

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]
[[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]


Problem 3

In [2]:
from numpy.linalg import eig
A = LA.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A,"\n")
w,v = LA.linalg.eig(A) 
print("The eigenvalue/s is/are:\n",w.round(),"\n")
print("The eigenvector/s is/are:\n",v.round())

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

The eigenvalue/s is/are:
 [-1.  3.  2.] 

The eigenvector/s is/are:
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
