<a href="https://colab.research.google.com/github/MichaelOblego/Linear-Algebra-58020/blob/main/Linear_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as LA
A = LA.array([[4,10,8],[10,26,26],[8,26,61]])
print(A)
inv_A = LA.linalg.inv(A)
print(inv_A)
B = LA.array([[44],[128],[214]])
print(B)
#AA^-1X = B.A^-1
X =LA.dot(inv_A,B)
print(X)

[[ 4 10  8]
 [10 26 26]
 [ 8 26 61]]
[[ 25.27777778 -11.16666667   1.44444444]
 [-11.16666667   5.          -0.66666667]
 [  1.44444444  -0.66666667   0.11111111]]
[[ 44]
 [128]
 [214]]
[[-8.]
 [ 6.]
 [ 2.]]
