<a href="https://colab.research.google.com/github/MichaelOblego/Linear-Algebra-58020/blob/main/Linear_Equation_Demo_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as LA

In [3]:
from scipy.linalg import solve

A = LA.array([[4,5],[3,-2]])
print(A)
B = LA.array([[7],[11]])
print(B)

X=LA.linalg.inv(A).dot(B)
print(X)

[[ 4  5]
 [ 3 -2]]
[[ 7]
 [11]]
[[ 3.]
 [-1.]]


In [4]:
inv_A = LA.linalg.inv(A)
print(inv_A)

X = LA.dot(inv_A,B)
print(X)

[[ 0.08695652  0.2173913 ]
 [ 0.13043478 -0.17391304]]
[[ 3.]
 [-1.]]


In [6]:
X = LA.linalg.solve(A,B)
print(X)

[[ 3.]
 [-1.]]


In [7]:
from scipy.linalg import solve
X = solve(A,B)
print(X)

[[ 3.]
 [-1.]]
