<a href="https://colab.research.google.com/github/MichaelOblego/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Midterm Exam

In [4]:
import numpy as LA

Question 1

In [27]:
smatrix = LA.identity(5)
print(f'Square Matrix whose length is 5: \n{smatrix}')

Square Matrix whose length is 5: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Question 2

In [31]:
utmatrix = LA.array([[1,2,3],
                    [0,3,1],
                    [0,0,5]])
print(utmatrix)

[[1 2 3]
 [0 3 1]
 [0 0 5]]


Question 3

In [29]:
smatrix =LA.array ([[1,2,3,4,5],
                         [2,1,2,3,4],
                         [3,2,1,2,3],
                         [4,3,2,1,2],
                         [5,4,3,2,1]])
print('the square matrix which is symmetrical')
print(smatrix)

the square matrix which is symmetrical
[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


Question 4

In [21]:
C = LA.array ([[1,2,3],[2,3,3],[3,4,-2]])

inverseC = LA.linalg.inv(C) 

print(inverseC)

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


Question 5

In [22]:
C = LA.array ([[1,2,3],[2,3,3],[3,4,-2]])

detC = LA.linalg.det(C)

print("Determinant of the given matrix in Question 4:  ")
print(int(detC))

Determinant of the given matrix in Question 4:  
5


Question 6

In [26]:
Eq = LA.array([[5,4,1],
                      [10,9,4],
                      [10,13,15]])

Con = LA.array([[[3.4],
                       [8.8],
                       [19.2]]])

roots = LA.linalg.inv(Eq) @Con

print(roots)

[[[0.2]
  [0.4]
  [0.8]]]
