<a href="https://colab.research.google.com/github/MichaelOblego/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Practical Lab Exam 1

In [8]:
import numpy as LA

In [13]:
W = LA.array([[1,-3,0],[2,-2,0],[3,1,0]])
X = LA.array([[3,2,1],[-1,2,3],[2,-1,1]])
Y = LA.array([[1,2,0],[0,-1,2],[0,0,0]])
Z = LA.array ([[0,1],[2,3]])

In [15]:
#a
output = LA.dot(W,Y)
print(output)

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


In [16]:
#b
output = LA.add(Z,Z)
print(output)

[[0 2]
 [4 6]]


In [17]:
#c
output = np.dot(3,X)
print(output)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


Problem #2

In [21]:
#a
A1=LA.cross(W,Y)
B2=2*A1
print(B2)

[[ 0  0 10]
 [-8 -8 -4]
 [ 0  0  0]]


In [22]:
#b
C1 = LA.dot(W,Y)
D2 = LA.subtract(C1,X)
print(D2)

[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]


In [23]:
#c
Z1 = LA.dot(Y,W)
X2 = 2*Z
Z1 = ([[5,-7],[4,4]])
V3 = LA.subtract(Z1,X2)
print(V3)

[[ 5 -9]
 [ 0 -2]]


#Statement B is True