<a href="https://colab.research.google.com/github/MichaelOblego/Linear-Algebra-58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Prelim Exam

In [1]:
import numpy as LA

Question 1

In [5]:
C = LA.eye(4)
print(C)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Question 2

In [6]:
B = C*2
print(B)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


Question 3

In [9]:
A = LA.array([2,7,4])
D = LA.array([3,9,8])
Output = LA.cross(A,D)
print("Cross-product: ", Output)

Cross-product:  [20 -4 -3]
