<a href="https://colab.research.google.com/github/MichaelOblego/Linear-Algebra-58020/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as LA

In [17]:
#Sum
A = LA.array([[-5,0],[4,1]])
B = LA.array([[6,3],[2,3]])
print(A+B)

[[1 3]
 [6 4]]


In [18]:
#Difference1
A = LA.array([[-5,0],[4,1]])
B = LA.array([[6,-3],[2,3]])
print(A-B)

[[-11   3]
 [  2  -2]]


In [19]:
#Difference2
A = LA.array([[-5,0],[4,1]])
B = LA.array([[6,-3],[2,3]])
print(B-B)

[[0 0]
 [0 0]]
