<a href="https://colab.research.google.com/github/MichaelOblego/Linear-Algebra-58020/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as LA

In [2]:
A = LA.array([[1,1,1],[1,2,2],[1,2,3]])
print(A)
inv_A = LA.linalg.inv(A)
print(inv_A)

[[1 1 1]
 [1 2 2]
 [1 2 3]]
[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  1.]]


In [3]:
B = LA.array([[5],[6],[8]])
print(B)
X = LA.dot(inv_A,B)
print(X)

[[5]
 [6]
 [8]]
[[ 4.]
 [-1.]
 [ 2.]]
