<a href="https://colab.research.google.com/github/MichaelOblego/Linear-Algebra-58020/blob/main/Vector_Representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
## Creating a 1x3 array (matrix)
a = np.array([1,1,1])
print(a)

[1 1 1]


In [5]:
## Creating a 2x3 matrix
b = np.array([[1,1,1],[2,2,2]]) 
print(b)

[[1 1 1]
 [2 2 2]]


In [6]:
## Creating a 3x3 matrix
c = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(c)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [7]:
## Creating a constant array with all values are constant
d =np.full([3,3],8) ## can use []
d_2 =np.full((3,3),0) ## <-- Square Matrix
print(d)
print(d_2)

[[8 8 8]
 [8 8 8]
 [8 8 8]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
## Creating a diagonal matrix
e = np.diagonal(c)
print(c)
print(e)

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[1 2 3]


In [9]:
## Creating an identity matrix
f = np.eye(6,dtype=int)
print(f)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [10]:
## Creating a zero matrix
g = np.zeros((4,8),dtype=int)
print(g)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [11]:
## Creating an empty matrix
h = np.empty((0,99))
h_2 = np.empty((5,2)) ## ??????
print(h)
print(h_2)

[]
[[4.66384841e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


In [12]:
## Addition of Matrices
i = np.array([[1,2,3],[4,5,6],[7,8,9]])
j = np.zeros((3,3),dtype=int) ## float + int = float; int + int = int
print(i+j)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
## Subtraction of Matrices
j = np.array([[-1,-2,-3],[-4,-5,-6],[-7,-8,-9]])
print(i-j)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
